function openSettings(){openModal(t('settingsTitle'),`<div class="settings-grid"><button id="exportBtn">↓ ${t('export')}</button><button id="importBtn">↑ ${t('import')}</button><button class="danger" id="clearBtn">× ${t('clear')}</button><button id="installHelp">⌂ ${t('install')}</button></div><p class="card-sub" style="margin-top:14px">${lang==='zh'?`当前存储：${DataStore.mode==='idb'?'IndexedDB':'LocalStorage'} · 云同步接口已预留，默认关闭。`:`Storage: ${DataStore.mode==='idb'?'IndexedDB':'LocalStorage'} · Cloud sync adapter is reserved and disabled by default.`}</p>`);qs('#exportBtn').onclick=exportData;qs('#importBtn').onclick=()=>qs('#importFile').click();qs('#clearBtn').onclick=clearData;qs('#installHelp').onclick=()=>{if(deferredInstall){closeModal();triggerInstall()}else alert(t('installIOS'))}}
  function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`life-workspace-backup-${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function importData(file){try{const obj=JSON.parse(await file.text());if(!obj||!obj.monthlyGoals||!obj.todos||!obj.notes||!obj.sleepChallenge||!obj.fitnessChallenge)throw new Error('bad');state=obj;await persist();closeModal();applyI18n();toast(t('imported'))}catch(e){toast(t('invalidImport'))}}
  async function clearData(){if(!confirm(t('clearConfirm')))return;await DataStore.clear();state=DataStore.defaults();await DataStore.save(state);closeModal();applyI18n();toast(t('saved'))}
  function triggerInstall(){if(!deferredInstall)return;deferredInstall.prompt();deferredInstall.userChoice.finally(()=>{deferredInstall=null;qs('#installBtn').classList.add('hidden')})}

  function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function bind(){qs('#langBtn').onclick=async()=>{lang=lang==='zh'?'en':'zh';state.settings.lang=lang;const u=new URL(location.href);if(lang==='en')u.searchParams.set('lang','en');else u.searchParams.delete('lang');history.replaceState(null,'',u);await persist();applyI18n()};qs('#settingsBtn').onclick=openSettings;qs('#editGoalBtn').onclick=openGoalEditor;qs('#historyBtn').onclick=openHistory;qs('#modalClose').onclick=closeModal;qs('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};qs('#todoAdd').onclick=addTodo;qs('#todoInput').onkeydown=e=>{if(e.key==='Enter')addTodo()};qs('#todoList').onclick=todoAction;qs('#todoPrev').onclick=()=>{todoDate=addDays(todoDate,-1);renderTodo()};qs('#todoNext').onclick=()=>{todoDate=addDays(todoDate,1);renderTodo()};qs('#saveNote').onclick=saveNote;qs('#noteSearch').oninput=renderNotes;qs('#noteFilter').onchange=renderNotes;qs('#timeline').onclick=noteAction;qs('#sleepCalendar').onclick=toggleChallenge;qs('#fitnessCalendar').onclick=toggleChallenge;qs('#rangeBtns').onclick=e=>{const b=e.target.closest('[data-range]');if(!b)return;analysisRange=+b.dataset.range;qsa('#rangeBtns button').forEach(x=>x.classList.toggle('active',x===b));renderAnalysis()};qs('#ideasList').onclick=async e=>{const b=e.target.closest('[data-copy]');if(!b)return;await navigator.clipboard.writeText(decodeURIComponent(b.dataset.copy));toast(t('copied'))};qs('#importFile').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};qs('#installBtn').onclick=triggerInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;qs('#installBtn').classList.remove('hidden')});window.addEventListener('offline',()=>showNet(false));window.addEventListener('online',()=>showNet(true))}
  function showNet(online){const el=qs('#netBanner');el.textContent=online?t('online'):t('offline');el.classList.remove('hidden');if(online)setTimeout(()=>el.classList.add('hidden'),1800)}
  async function registerSW(){if(!('serviceWorker' in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js');reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller){const el=qs('#netBanner');el.innerHTML=`${t('newVersion')} · <button id="refreshNow" style="border:0;background:transparent;color:white;text-decoration:underline;font-weight:800">${t('refresh')}</button>`;el.classList.remove('hidden');qs('#refreshNow').onclick=()=>{w.postMessage({type:'SKIP_WAITING'});location.reload()}}})})}catch(e){console.warn('SW unavailable',e)}}
  async function init(){state=await DataStore.init();const urlLang=new URL(location.href).searchParams.get('lang');lang=urlLang==='en'?'en':(state.settings.lang||'zh');bind();applyI18n();registerSW()}
  init();
