function renderHeader(){const d=new Date(),h=d.getHours();const gi=h<12?0:h<18?1:2;qs('#greeting').textContent=t('greetings')[gi];qs('#todayText').textContent=lang==='zh'?`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日 · ${t('week')[d.getDay()]}`:new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(d);qs('#quote').textContent=t('quotes')[d.getDate()%t('quotes').length];qs('#brandLine').textContent=lang==='zh'?'更广阔 · 更自由 · 更轻松':'Broader · Freer · Lighter';qs('#monthLabel').textContent=lang==='zh'?`${d.getFullYear()} · ${t('monthNames')[d.getMonth()]}`:`${t('monthNames')[d.getMonth()].toUpperCase()} · ${d.getFullYear()}`}
  function renderGoal(){const g=ensureGoal();qs('#goalTitle').textContent=lang==='zh'?(g.titleZh||g.titleEn):(g.titleEn||g.titleZh);qs('#goalDesc').textContent=g.description|| (lang==='zh'?'用一个月，只守住最重要的生活主线。':'Keep one important life theme for the whole month.')}
  function openModal(title,html){qs('#modalTitle').textContent=title;qs('#modalBody').innerHTML=html;qs('#modal').classList.remove('hidden')}
  function closeModal(){qs('#modal').classList.add('hidden')}
  function openGoalEditor(){const g=ensureGoal();openModal(t('editGoal'),`<div class="form-stack"><label>${t('goalTitle')}<input id="gTitle" class="input" value="${escapeHtml(lang==='zh'?(g.titleZh||''):(g.titleEn||''))}"></label><label>${t('goalDesc')}<textarea id="gDesc" class="textarea">${escapeHtml(g.description||'')}</textarea></label><label>${t('goalTarget')}<input id="gTarget" class="input" value="${escapeHtml(g.target||'')}"></label><label>${t('goalReview')}<textarea id="gReview" class="textarea">${escapeHtml(g.review||'')}</textarea></label></div><div class="modal-actions"><button class="pill" id="goalCancel">${t('cancel')}</button><button class="pill primary" id="goalSave">${t('save')}</button></div>`);qs('#goalCancel').onclick=closeModal;qs('#goalSave').onclick=async()=>{if(lang==='zh')g.titleZh=qs('#gTitle').value.trim();else g.titleEn=qs('#gTitle').value.trim();g.description=qs('#gDesc').value.trim();g.target=qs('#gTarget').value.trim();g.review=qs('#gReview').value.trim();g.updated_at=new Date().toISOString();await persist();closeModal();renderGoal();toast(t('saved'))}}
  function openHistory(){const items=[...state.monthlyGoals].sort((a,b)=>b.month.localeCompare(a.month));openModal(t('historyTitle'),items.length?items.map(g=>`<div class="history-item"><strong>${g.month} · ${escapeHtml(lang==='zh'?(g.titleZh||g.titleEn):(g.titleEn||g.titleZh))}</strong>${g.target?`<p>${escapeHtml(g.target)}</p>`:''}${g.review?`<p>${escapeHtml(g.review)}</p>`:''}</div>`).join(''):`<div class="empty">${t('emptyHistory')}</div>`)}

  function renderTodo(){const d=parseDate(todoDate);qs('#todoDate').textContent=lang==='zh'?`${d.getMonth()+1}月${d.getDate()}日 · ${t('week')[d.getDay()]}`:new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',weekday:'short'}).format(d);const list=(state.todos[todoDate]||[]).sort((a,b)=>a.sort-b.sort),done=list.filter(x=>x.completed).length,p=list.length?Math.round(done/list.length*100):0;qs('#todoPct').textContent=`${p}%`;qs('#todoProgress').style.width=`${p}%`;qs('#todoCount').textContent=t('todoCount',done,list.length);qs('#todoList').innerHTML=list.map(x=>`<div class="todo-row"><button class="check ${x.completed?'done':''}" data-action="toggle" data-id="${x.id}" aria-label="toggle">${x.completed?'✓':''}</button><div class="todo-text ${x.completed?'done':''}" data-action="edit" data-id="${x.id}" title="double click to edit">${escapeHtml(x.title)}</div><button class="delete" data-action="delete" data-id="${x.id}" aria-label="delete">×</button></div>`).join('')||`<div class="empty">${lang==='zh'?'今天还没有待办。':'No to-dos yet.'}</div>`}
  async function addTodo(){const input=qs('#todoInput'),v=input.value.trim();if(!v)return;state.todos[todoDate] ||= [];state.todos[todoDate].push({id:uid(),title:v,completed:false,sort:state.todos[todoDate].length,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});input.value='';await persist();renderTodo()}
  async function todoAction(e){const el=e.target.closest('[data-action]');if(!el)return;const list=state.todos[todoDate]||[],item=list.find(x=>x.id===el.dataset.id);if(!item)return;if(el.dataset.action==='toggle')item.completed=!item.completed;else if(el.dataset.action==='delete')state.todos[todoDate]=list.filter(x=>x.id!==item.id);else if(el.dataset.action==='edit'){const next=prompt(lang==='zh'?'编辑待办':'Edit to-do',item.title);if(next?.trim())item.title=next.trim();else return}item.updated_at=new Date().toISOString();await persist();renderTodo()}

  function renderNoteOptions(){const c=qs('#noteCategory'),m=qs('#noteMood'),f=qs('#noteFilter'),oldC=c.selectedIndex,oldM=m.selectedIndex,oldF=f.value;c.innerHTML=t('categories').map((x,i)=>`<option value="${i}">${x}</option>`).join('');m.innerHTML=t('moods').map((x,i)=>`<option value="${i}">${x}</option>`).join('');f.innerHTML=`<option value="all">${t('all')}</option>`+t('categories').map((x,i)=>`<option value="${i}">${x}</option>`).join('');c.selectedIndex=Math.max(0,oldC);m.selectedIndex=Math.max(0,oldM);if(oldF)f.value=oldF}
  async function saveNote(){const text=qs('#noteText').value.trim();if(!text)return;const now=new Date();state.notes.push({id:uid(),date:localDate(now),time:`${pad(now.getHours())}:${pad(now.getMinutes())}`,category:+qs('#noteCategory').value,mood:+qs('#noteMood').value,content:text,created_at:now.toISOString(),updated_at:now.toISOString()});qs('#noteText').value='';await persist();renderNotes();renderAnalysis();toast(t('saved'))}
  function renderNotes(){const query=qs('#noteSearch').value.trim().toLowerCase(),filter=qs('#noteFilter').value;let notes=[...state.notes].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));notes=notes.filter(n=>(filter==='all'||String(n.category)===filter)&&(!query||n.content.toLowerCase().includes(query)));const groups={};notes.forEach(n=>(groups[n.date] ||= []).push(n));const html=Object.entries(groups).map(([date,arr])=>{const d=parseDate(date),label=lang==='zh'?`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日` : new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d);return `<div class="daygroup"><div class="daylabel">${label}</div>${arr.map(n=>`<article class="note"><div class="note-meta"><div class="note-tags"><span class="tag">${t('categories')[n.category]||''}</span><span>${t('moods')[n.mood]||''}</span><span>${n.time}</span></div><div class="note-tools"><button data-note-edit="${n.id}">✎</button><button data-note-del="${n.id}">×</button></div></div><div class="note-body">${escapeHtml(n.content)}</div></article>`).join('')}</div>`}).join('');qs('#timeline').innerHTML=html||`<div class="empty">${t('noNotes')}</div>`}
  async function noteAction(e){const id=e.target.dataset.noteDel||e.target.dataset.noteEdit;if(!id)return;const n=state.notes.find(x=>x.id===id);if(!n)return;if(e.target.dataset.noteDel){state.notes=state.notes.filter(x=>x.id!==id);toast(t('deleted'))}else{const next=prompt(lang==='zh'?'编辑记录':'Edit note',n.content);if(next?.trim())n.content=next.trim();else return;n.updated_at=new Date().toISOString()}await persist();renderNotes();renderAnalysis()}

  function challengeData(kind){return kind==='sleep'?state.sleepChallenge:state.fitnessChallenge}
  function calcStreak(ch){const max=Math.max(0,Math.min(20,daysBetween(ch.startDate,todayKey())));let end=max;if(!ch.checkins[String(end)]&&end>0)end--;let streak=0;for(let i=end;i>=0;i--){if(ch.checkins[String(i)])streak++;else break}return streak}
  function renderChallenge(kind){const ch=challengeData(kind),cal=qs(kind==='sleep'?'#sleepCalendar':'#fitnessCalendar'),streak=calcStreak(ch),total=Object.values(ch.checkins).filter(Boolean).length;const sd=parseDate(ch.startDate),ed=parseDate(addDays(ch.startDate,20));qs(kind==='sleep'?'#sleepStreak':'#fitnessStreakNum').textContent=streak;qs(kind==='sleep'?'#sleepTotal':'#fitnessTotal').textContent=t('total',total);qs(kind==='sleep'?'#sleepRange':'#fitnessRange').textContent=`${pad(sd.getMonth()+1)}.${pad(sd.getDate())} → ${pad(ed.getMonth()+1)}.${pad(ed.getDate())}`;cal.innerHTML=Array.from({length:21},(_,i)=>{const d=parseDate(addDays(ch.startDate,i)),done=!!ch.checkins[String(i)];return `<button class="daycell ${done?'done':''}" data-kind="${kind}" data-day="${i}" aria-label="day ${i+1}"><span class="n">${pad(i+1)} ${done?'✓':''}</span><span class="d">${pad(d.getMonth()+1)}.${pad(d.getDate())}</span></button>`}).join('')}
  async function toggleChallenge(e){const cell=e.target.closest('.daycell');if(!cell)return;const ch=challengeData(cell.dataset.kind),k=cell.dataset.day;ch.checkins[k]=!ch.checkins[k];await persist();renderChallenge(cell.dataset.kind);if(Object.values(ch.checkins).filter(Boolean).length===21)showCongrats(cell.dataset.kind)}
  function showCongrats(kind){openModal(t('congrats'),`<div class="celebrate"><div class="big">${kind==='sleep'?'📱':'🏃'}</div><h3>${t('congrats')}</h3><p>${kind==='sleep'?t('congratsBody'):t('fitnessCongratsBody')}</p><button class="pill primary" onclick="document.querySelector('#modalClose').click()">OK</button></div>`)}

  const stopZh=new Set('的 了 是 我 你 他 她 它 和 与 在 有 就 都 而 及 被 把 让 又 也 很 还 一个 一些 这个 那个 今天 昨天 现在 其实 觉得 感觉 发现 时候 因为 所以 如果 但是 然后 进行 可以 需要 还是 比较 可能'.split(' '));
  const stopEn=new Set('the a an and or but if then is are was were be been being i you he she it we they this that these those to of in on at for from with as by today yesterday really just very can could should would'.split(' '));
  const templatesZh=['为什么{a}真正难的不是表面问题，而是底层机制','从一次{a}经历，我重新理解了{b}','用了{a}之后，我发现真正拉开差距的是{b}','关于{a}，大多数人忽略了这一个细节','如果重新做一次{a}，我会先做这三件事','从{a}到{b}：一个普通人的实践路径','{a}为什么越来越重要？我的三个观察','我在{a}上踩过的坑，最后都指向{b}','工作几年后，我开始重新理解{a}','把{a}做简单，比把它做复杂更难','一次{a}问题，暴露出系统协作的三个盲区','关于{a}，经验主义什么时候会失效','我如何用{a}减少工作里的重复消耗','{a}不是工具问题，而是工作方式问题','从{a}看产品经理真正该负责什么','为什么稳定做{a}比偶尔爆发更重要','关于{a}，我最近改变了一个判断','普通人如何建立自己的{a}能力曲线','{a}与{b}之间，真正缺的是这一层','一次失败的{a}，比十次顺利更值得复盘','当{a}遇到真实业务，最先失效的是什么','我如何判断一个{a}方案到底靠不靠谱','关于{a}的五个反常识判断','为什么{a}做得越多，越需要做减法','从维修现场看{a}：问题往往不在问题本身','如果只保留一个{a}习惯，我会选什么','关于{a}，我更愿意相信长期数据而不是短期感觉','把{a}写下来后，我看见了自己的思考模式','{a}背后真正值得积累的，是可迁移能力','从{a}出发，如何获得更自由的工作方式'];
  const templatesEn=['Why the hardest part of {a} is not the visible problem','What one {a} experience taught me about {b}','After using {a}, I realized {b} creates the real gap','The detail most people miss about {a}','If I did {a} again, I would start with these three things','From {a} to {b}: a practical path','Why {a} matters more now: three observations','The mistakes I made with {a} all pointed to {b}','After a few years of work, I see {a} differently','Making {a} simple is harder than making it complex','One {a} issue exposed three collaboration blind spots','When experience stops working in {a}','How I use {a} to reduce repetitive work','{a} is not a tool problem. It is a workflow problem','What product managers should really own in {a}','Why consistency in {a} beats occasional intensity','One opinion I recently changed about {a}','How ordinary people can build a durable {a} skill curve','The missing layer between {a} and {b}','Why a failed {a} is worth more reflection than ten smooth wins','What breaks first when {a} meets real business','How I judge whether a {a} solution is actually reliable','Five counterintuitive lessons about {a}','Why doing more {a} makes subtraction more important','What field repairs teach us about {a}','If I kept only one {a} habit, it would be this','Why I trust long-term data over short-term feeling in {a}','Writing about {a} revealed my own thinking pattern','The transferable skill behind {a}','How {a} can lead to a freer way of working'];
  function wordsFrom(text){if(lang==='zh'){const matches=text.match(/[\u4e00-\u9fff]{2,8}|[A-Za-z][A-Za-z0-9+-]{1,20}/g)||[];return matches.filter(w=>!stopZh.has(w)&&w.length>1)}return (text.toLowerCase().match(/[a-z][a-z0-9+-]{2,}/g)||[]).filter(w=>!stopEn.has(w))}
  function renderAnalysis(){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-analysisRange+1);const notes=state.notes.filter(n=>parseDate(n.date)>=new Date(cutoff.getFullYear(),cutoff.getMonth(),cutoff.getDate()));if(!notes.length){qs('#keywordChips').innerHTML=`<span class="muted">${t('noData')}</span>`;qs('#moodAnalysis').innerHTML=`<span class="muted">${t('noData')}</span>`;qs('#ideasList').innerHTML=`<span class="muted">${t('noData')}</span>`;return}const counts={};notes.flatMap(n=>wordsFrom(n.content)).forEach(w=>counts[w]=(counts[w]||0)+1);const keywords=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]);qs('#keywordChips').innerHTML=keywords.length?keywords.map(w=>`<span class="chip">${escapeHtml(w)}</span>`).join(''):`<span class="muted">—</span>`;const moods={};notes.forEach(n=>moods[n.mood]=(moods[n.mood]||0)+1);qs('#moodAnalysis').innerHTML=Object.entries(moods).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div style="display:flex;justify-content:space-between;gap:10px;margin:8px 0"><span>${t('moods')[+k]||''}</span><strong>${Math.round(v/notes.length*100)}%</strong></div>`).join('');const a=keywords[0]||(lang==='zh'?'工作':'work'),b=keywords[1]||(lang==='zh'?'成长':'growth'),templates=lang==='zh'?templatesZh:templatesEn;const ideas=templates.slice(0,5).map((tpl,i)=>tpl.replaceAll('{a}',a).replaceAll('{b}',b));qs('#ideasList').innerHTML=ideas.map((idea,i)=>`<div class="idea"><span class="idea-num">0${i+1}</span><span>${escapeHtml(idea)}</span><button class="copy" data-copy="${encodeURIComponent(idea)}">${lang==='zh'?'复制':'Copy'}</button></div>`).join('')}
